### ISSUE TITLE
안녕하세요~ 코드가 실시간으로 업데이트 되는게 흥미롭네요

### ISSUE THREAD

**Issue by JeongJaeSoon** [LeeJaeBae/blog-project#1]
안녕하세요~ 
코드가 실시간으로 업데이트 되는게 흥미롭네요
기술스택이 어떻게 되는지 알 수 있을까요?

**Comment by LeeJaeBae** [comment]
네 안녕하세요~
이번 프로젝트는 언어는 Typescript를 주로 사용해서
GraphQL 서버를 이용해서 프로젝트를 진행하고 있어요!

DB는 Postgresql을 활용하고 프론트엔드는 리액트를 사용할 예정입니다~

**Comment by JeongJaeSoon** [comment]
아... 일방적으로 닫겨버렸네요..
PostgreSQL 을 쓰는 이유가 있으실까요?

**Comment by LeeJaeBae** [comment]
문단속은 철저히 하는 편입니다.

현재 일본 취업을 준비하고 있는데, 일본에서 많이 사용하는 DB에 익숙해지고 싶어서 선택했습니다!

**Comment by JeongJaeSoon** [comment]
@LeeJaeBae 아 그렇군요!! 힘내서 잘 해봐요!!

**Comment by LeeJaeBae** [comment]
@JeongJaeSoon 넵 응원 감사합니다!
